### ISSUE TITLE
[bug]: Replacing bluebird + whatwg-fetch to polyfill.io caused error in IE11

### ISSUE THREAD

**Issue by viT-1** [Financial-Times/polyfill-service#2020]
## What
I have a typescript project with SystemJS bundling.
Until recently (with bluebird Promise & whatwg-fetch) it was ok, but [this project](https://github.com/viT-1/systemjs-ts-es6-vue) is only test for our product (in which we use polyfill.io polyfills).

## Details
Label "Test SystemJS & Vue" should be green (if all is ok & vue initiated).
Reproduce:
- change [this lines](https://github.com/viT-1/systemjs-ts-es6-vue/blob/401f275f0f2395a2a46843aae87d4df39eb7bffe/src/index.htm#L4-L7) to
`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Promise"></script>`
- npm run deploy
- npm run www
- open IE11 & open changed index.htm on http://localhost:3000/
- open console & see:
SystemJs bundle is loaded! - it's fine (SystemJS seems to be Ok)
Uncaught (in promise) TypeError: ...

- repeat this steps without first step - label is green now!

IE 11.737.17763.0
Windows 10 (Desktop)

## Additional information
[Issue on SystemJS](https://github.com/systemjs/systemjs/issues/2037) about this.

**Comment by JakeChampion** [comment]
Hi, I can't use debug your project, could you please provide a small reproducible test case that only includes the necessary code to have the error happen, that way we can hopefully see exactly what is going on. I did try to run your project but it has dependencies which are not on npmjs public registry. (`Could not find dependency: '@common/GreeterUse' relative to '/src/main.ts'`)

**Comment by viT-1** [comment]
@common/GreeterUse is matched by [tsconfig.json](https://github.com/viT-1/systemjs-ts-es6-vue/blob/master/src/tsconfig.json#L11) to `src/common.blocks/GreeterUse`
Why npmjs?!

**Comment by JakeChampion** [comment]
Are you able to create a small reproducible test case instead of an entire application to run? If so, that would greatly help in being able to help debug this potential issue on polyfill.io

**Comment by viT-1** [comment]
This project is smallest as possible bundle with SystemJS, Vue & vue-class-component

**Comment by JakeChampion** [comment]
Does the issue occur without including Vue & vue-class-component?

**Comment by viT-1** [comment]
I'll try to run this project without vue-class-component decorator, though.

**Comment by viT-1** [comment]
Excluding vue-class-component from my project is not helped.
Excluding vue initialization (commented out two lines: [import](https://github.com/viT-1/systemjs-ts-es6-vue/blob/60e4f6df7919829e2e7424597eb3a25165558687/src/main.ts#L2) & init) is helped.

**Comment by viT-1** [comment]
just [commented out](https://github.com/viT-1/systemjs-ts-es6-vue/commit/357000a9c509a57150f9291dee395f3fc8fad386) vue-component IamHeader
vue is initiated with SystemJS though
and have all browsers console:
```
SystemJs bundle is loaded!
Main entry file is Ok!
Nice to see you, world
```

and IE11 only stack trace:
```
Uncaught (in promise) TypeError: Не удалось получить свойство "default" ссылки, значение которой не определено или является NULL
   at VueApp.init (http://localhost:3000/bundle.js:436:21)
   at execute (http://localhost:3000/bundle.js:482:13)
   at doExec (http://localhost:3000/systemjs/system.js:439:9)
   at postOrderExec (http://localhost:3000/systemjs/system.js:435:5)
   at Anonymous function (http://localhost:3000/systemjs/system.js:386:7)
   at g (https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Promise:3:2161)
   at s (https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Promise:3:679)
   at Anonymous function (https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Promise:3:4423)
   at r (https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Promise:3:813)
```

**Comment by viT-1** [comment]
Instead of polyfill.io I tried also
`https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js`
&
`https://cdn.jsdelivr.net/npm/cross-fetch@3.0.4/dist/cross-fetch.js`
and everything is ok,
but i need polyfill.io version in production =(

**Comment by viT-1** [comment]
Found 'always'-workaround [here](https://github.com/Financial-Times/polyfill-service/issues/1428#issuecomment-460691928):
https://cdn.polyfill.io/v3/polyfill.min.js?flags=always
& bluebird + whatwg-fetch (or other realisation pair Promise +fetch)

PS: but with `SCRIPT5022: HierarchyRequestError`

**Comment by JakeChampion** [comment]
@viT-1 If using `always` I would recommend also using `gated` to ensure polyfills are only applied when the native feature is missing `https://cdn.polyfill.io/v3/polyfill.min.js?flags=always,gated&features=default,fetch,Promise`

**Comment by viT-1** [comment]
But why I need 'always'? Is it dirty hack?!

**Comment by viT-1** [comment]
@JakeChampion fetch & Promise from polyfill.io is not worked, I use other providers.
I need to make polyfill.io script to working without destroying effect on SystemJs.

**Comment by viT-1** [comment]
[Related](https://github.com/Financial-Times/polyfill-service/issues/2018)

**Comment by viT-1** [comment]
May be [related](https://github.com/vuejs/vue/issues/10510)?

**Comment by viT-1** [comment]
Dirty workaround from 2016 is working for me:
`https://cdn.polyfill.io/v3/polyfill.js?flags=always,gated&excludes=Symbol,Symbol.iterator,Symbol.species`
Will it ever be fixed?

**Comment by viT-1** [comment]
Using polyfill.io Promise without default & excludes also working (but not fetch!)
https://cdn.polyfill.io/v3/polyfill.min.js?flags=always,gated&features=Promise
+
https://cdn.jsdelivr.net/npm/whatwg-fetch@3.0.0/dist/fetch.umd.min.js
or
https://cdn.jsdelivr.net/npm/cross-fetch@3.0.4/dist/cross-fetch.js
